<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926"/>
  <!--驱动轮半径-->
  <xacro:property name="drive_wheel_radius" value="0.125"/>
  <!--caster轮半径-->
  <xacro:property name="caster_wheel_radius" value="0.12"/>
  <!--底盘高度-->
  <xacro:property name="chassis_height" value="0.285"/>
  <!--底盘厚度-->
  <xacro:property name="chassis_thickness" value="0.015"/>
  <!--滚珠高度-->
  <xacro:property name="ball_thickness" value="0.024"/>
  <!--轮间距-->
  <xacro:property name="wheel_spacing" value="0.22"/>

  <xacro:property name="wheel_spacing_sqrt" value="0.3111269837220809"/>
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find agv_diff_description)/urdf/agv.gazebo" />

  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
     </visual>
  </link>
  <!--chassis-->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <mass value="42.29" />
      <inertia
        ixx="2.6315755990863"
        ixy="0.0281997656512484"
        ixz="8.56689328317458E-19"
        iyy="2.6315755990863"
        iyz="1.6205417368533E-16"
        izz="5.26033184972975" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 -${M_PI/4}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/base_link_small.STL" />
      </geometry>
      <material name="">
        <color rgba="0.898039215686275 0.917647058823529 0.929411764705882 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 -${M_PI/4}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/base_link_small.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${chassis_height}" rpy="0 0 0" />        
      <parent link="base_footprint"/>
        <child link="base_link" />
  </joint>
  <!--turnning_wheel_A-->
  <link name="turnning_wheel_A">
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <mass value="42.11" />
      <inertia
        ixx="0.47711"
        ixy="0.044321"
        ixz="0.053517"
        iyy="0.45428"
        iyz="-0.049111"
        izz="0.57664" />
    </inertial>
    <visual>
      <origin xyz="0 0 -${ball_thickness}" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/turnning_joint.STL" />
      </geometry>
      <material name="">
        <color rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -${ball_thickness}" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/turnning_joint.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="turnning_wheel_joint_A" type="fixed">
    <origin xyz="0 ${wheel_spacing_sqrt} 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="turnning_wheel_A" />
    <axis xyz="0 0 1" />
	<limit effort="100" velocity="50"/>
  </joint>
  <!--drive_wheel_A-->
  <link name="drive_wheel_A">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="4.1674" />
      <inertia
        ixx="0.019462933072448"
        ixy="-1.73192142405451E-35"
        ixz="7.50885510983801E-19"
        iyy="0.019462933072448"
        iyz="-7.72409252183777E-35"
        izz="0.0352867632665584" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/drive_wheel.STL" />
      </geometry>
      <material name="">
        <color rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/drive_wheel.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="drive_wheel_joint_A" type="continuous">
    <origin xyz="0 0 -${chassis_height-drive_wheel_radius+chassis_thickness}" rpy="0 0 0"/>
	<parent link="turnning_wheel_A"/>
	<child link="drive_wheel_A"/>
    <axis xyz="0 1 0"/>
	<limit effort="100" velocity="50"/>
  </joint>
  <!--turnning_wheel_B-->
  <link name="turnning_wheel_B">
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <mass value="42.11" />
      <inertia
        ixx="0.47711"
        ixy="0.044321"
        ixz="0.053517"
        iyy="0.45428"
        iyz="-0.049111"
        izz="0.57664" />
    </inertial>
    <visual>
      <origin xyz="0 0 -${ball_thickness}" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/turnning_joint.STL" />
      </geometry>
      <material name="">
        <color rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -${ball_thickness}" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/turnning_joint.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="turnning_wheel_joint_B" type="fixed">
    <origin xyz="0 -${wheel_spacing_sqrt} 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="turnning_wheel_B" />
    <axis xyz="0 0 1" />
	<limit effort="100" velocity="50"/>
  </joint>
  <!--drive_wheel_B-->
  <link name="drive_wheel_B">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="4.1674" />
      <inertia
        ixx="0.019462933072448"
        ixy="-1.73192142405451E-35"
        ixz="7.50885510983801E-19"
        iyy="0.019462933072448"
        iyz="-7.72409252183777E-35"
        izz="0.0352867632665584" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/drive_wheel.STL" />
      </geometry>
      <material name="">
        <color rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/drive_wheel.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="drive_wheel_joint_B" type="continuous">
    <origin xyz="0 0 -${chassis_height-drive_wheel_radius+chassis_thickness}" rpy="0 0 0"/>
	<parent link="turnning_wheel_B"/>
	<child link="drive_wheel_B"/>
    <axis xyz="0 1 0"/>
	<limit effort="100" velocity="50"/>
  </joint>
  <!--caster_axis_A-->
  <link name="caster_axis_A">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.742" />
      <inertia
        ixx="0.00684293124408651"
        ixy="-5.72533127736967E-06"
        ixz="1.86434678810828E-06"
        iyy="0.00276843943664337"
        iyz="0.00105696596367239"
        izz="0.00759513267231257" />
    </inertial>
    <visual>
      <origin xyz="0 0 -0.005" rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_axis.STL" />
      </geometry>
      <material name="">
        <color rgba="0.77647 0.75686 0.73725 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.005" rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_axis.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_axis_joint_A" type="continuous">
    <origin xyz="${wheel_spacing_sqrt} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
	<child link="caster_axis_A"/>
	<axis xyz="0 0 1"/>
  </joint>

  <!--caster_wheel_A-->
  <link name="caster_wheel_A">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="3.1637" />
      <inertia
        ixx="0.0119781194667373"
        ixy="3.60595347707088E-24"
        ixz="-9.35749979388708E-23"
        iyy="0.0119781194667373"
        iyz="4.4067452325737E-07"
        izz="0.0222232621882072" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_wheel.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_wheel_joint_A" type="continuous">
    <origin xyz="0.03 0 -${chassis_height-caster_wheel_radius+chassis_thickness}" rpy="0 0 0"/>
	<parent link="caster_axis_A"/>
	<child link="caster_wheel_A"/>
	<axis xyz="0 1 0"/>
  </joint>

  <!--caster_axis_B-->
  <link name="caster_axis_B">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1.742" />
      <inertia
        ixx="0.00684293124408651"
        ixy="-5.72533127736967E-06"
        ixz="1.86434678810828E-06"
        iyy="0.00276843943664337"
        iyz="0.00105696596367239"
        izz="0.00759513267231257" />
    </inertial>
    <visual>
      <origin xyz="0 0 -0.005" rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_axis.STL" />
      </geometry>
      <material name="">
        <color rgba="0.77647 0.75686 0.73725 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.005" rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_axis.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_axis_joint_B" type="continuous">
    <origin xyz="-${wheel_spacing_sqrt} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
	<child link="caster_axis_B"/>
	<axis xyz="0 0 1"/>
  </joint>

  <!--caster_wheel_B-->
  <link name="caster_wheel_B">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="3.1637" />
      <inertia
        ixx="0.0119781194667373"
        ixy="3.60595347707088E-24"
        ixz="-9.35749979388708E-23"
        iyy="0.0119781194667373"
        iyz="4.4067452325737E-07"
        izz="0.0222232621882072" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://agv_diff_description/meshes/caster_wheel.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_wheel_joint_B" type="continuous">
    <origin xyz="0.03 0 -${chassis_height-caster_wheel_radius+chassis_thickness}" rpy="0 0 0"/>
	<parent link="caster_axis_B"/>
	<child link="caster_wheel_B"/>
	<axis xyz="0 1 0"/>
  </joint>

</robot>
